In [74]:
import numpy as np
import re
from scipy.spatial import distance

In [2]:
a = open("_3a8d746cf4d86fba2f31586f239d11fd_sentences.txt", "r")
b = a.read().lower()
test_ = b.split('\n')
test_ = ','.join(test_)
pred = test_.split('.,')
pred = pred[:22]
res =re.split('[^a-z]',b)

In [29]:
for a in range(100):
    for i in range(len(res) - 1):
        if res[i] ==  '':
            res.pop(i)


IndexError: list index out of range

In [34]:
res = list(set(res))

In [42]:
i = 0
words_dict = {i:res[i] for i in range(len(res))}

In [43]:
print(words_dict)

{0: 'unnecessary', 1: 'mice', 2: 'basic', 3: 'useful', 4: 'those', 5: 'closest', 6: 'just', 7: 'genes', 8: 'one', 9: 'its', 10: 'any', 11: 'hear', 12: 'received', 13: 'started', 14: 'is', 15: 'information', 16: 'linux', 17: 'longer', 18: 'files', 19: 'symbol', 20: 'on', 21: 'store', 22: 'small', 23: 'world', 24: 'moved', 25: 'based', 26: 'to', 27: 'october', 28: 'patch', 29: 'command', 30: 'switch', 31: 'arguments', 32: 'redirection', 33: 'create', 34: 'default', 35: 'marks', 36: 'now', 37: 'such', 38: 'legibility', 39: 'computers', 40: 'some', 41: 'fifth', 42: 'editions', 43: 'weighing', 44: 'x', 45: 'from', 46: 'piped', 47: 'versions', 48: 'in', 49: 'selection', 50: 'roughly', 51: 'safer', 52: 'using', 53: 'without', 54: 'concatenate', 55: 'part', 56: 'download', 57: 'releasing', 58: 'stdin', 59: 'installed', 60: 'possess', 61: 'between', 62: 'you', 63: 'pipes', 64: 'made', 65: 'has', 66: 'needing', 67: 'however', 68: 'symbols', 69: 'app', 70: 'a', 71: 'most', 72: 'people', 73: 'comp

In [45]:
for i in range(len(pred)):
    pred[i] = re.split('[^a-z]',pred[i])

In [46]:
print(pred)

[['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', '', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], ['in', 'one', '', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', '', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'bot

In [64]:
a = 0
for i in pred:
    for a in i:
        if a == '':
            i.remove(a)

In [65]:
print(pred)

[['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organism

In [95]:
result_matrix = np.zeros((22,254))

In [97]:
for i in range(len(result_matrix)):
    for key in words_dict:
        for a in range(len(pred[i])):
            if words_dict[key] == pred[i][a]:
                result_matrix[i][key] += 1
        

In [98]:
print(result_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [92]:
print(result_matrix[1])

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]


AttributeError: module 'scipy' has no attribute 'spatial'

In [100]:
for i in range(22):
    print(i)
    print(distance.cosine(result_matrix[0],result_matrix[i]))
    print('========')

0
0.0
1
0.9527544408738466
2
0.8644738145642124
3
0.8951715163278082
4
0.7770887149698589
5
0.9402385695332803
6
0.7327387580875756
7
0.9258750683338899
8
0.8842724875284311
9
0.9055088817476932
10
0.8328165362273942
11
0.8804771390665607
12
0.8396432548525454
13
0.8703592552895671
14
0.8740118423302576
15
0.9442721787424647
16
0.8406361854220809
17
0.956644501523794
18
0.9442721787424647
19
0.8885443574849294
20
0.8427572744917122
21
0.8250364469440588


In [103]:
new_file = open("submission_cats.txt", "w+")
new_file.write = ("6 4")
new_file.close()